### PR TITLE
Autoinstall dependencies

### PR DESCRIPTION
**Pull request by gloomy-ghost**
Well, sorry for PRs before.
I've created a config file to put dependencies info, please merge it if you think it's ok

### CODE REVIEW

**Comment by jgmdev** [comment]
Nice solution, thanks!

**Comment by jgmdev** [comment]
Question, Did you tested with yum to see if it is executing properly? I think instead of **yum install -y**, it is evaluating to **yum*/ install -y** so removing the */ at the end would fix it.

**Comment by gloomy-ghost** [comment]
You are right, but I would like to remain the first line as a comment.
Are you happy with the new PR? I've tested it on CentOS 7 & Ubuntu 1404 and it works on both systems.

**Comment by jgmdev** [comment]
instead of using /* */ for comment you can use a # at beginning of line and it suits better the sh stuff.

**Pull request merged**
